function [fitresult, gof, output] = createFit(x200, y200)
%CREATEFIT(X200,Y200)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x200
%      Y Output: y200
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Oct-2014 11:58:10


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x200, y200 );

% Set up fittype and options.
ft = fittype( 'y0 + (AG/(wG*sqrt(2*pi)))*exp(-((x-xc)/(sqrt(2)*wG))^2) + (AL/pi)*(wL./((x-xc)^2 + wL^2)) + (AG2/(wG2*sqrt(2*pi)))*exp(-((x-xc2)/(sqrt(2)*wG2))^2) + (AL2/pi)*(wL2./((x-xc2)^2 + wL2^2))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0 0 0 29.8 29.8 0];
opts.StartPoint = [0.546881519204984 0.957506835434298 0.964888535199277 0.157613081677548 0.970592781760616 0.957166948242946 0.485375648722841 0.8002804688888 0.141886338627215 0.421761282626275 0.915735525189067];
opts.Upper = [Inf Inf Inf Inf 0.2 0.2 0.2 0.2 30.2 30.2 1000];

% Fit model to data.
[fitresult, gof, output] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y200 vs. x200', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x200' );
ylabel( 'y200' );
grid on


