function [fitresult, gof, output] = createFit(x400, y400)
%CREATEFIT(X200,Y200)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x200
%      Y Output: y200
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Oct-2014 11:58:10


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x400, y400 );

% Set up fittype and options.
ft = fittype( 'y0 + (AG/(wG*sqrt(2*pi)))*exp(-((x-xc)/(sqrt(2)*wG))^2) + (AL/pi)*(wL./((x-xc)^2 + wL^2)) + (AG2/(wG2*sqrt(2*pi)))*exp(-((x-xc2)/(sqrt(2)*wG2))^2) + (AL2/pi)*(wL2./((x-xc2)^2 + wL2^2))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0 0 0 62 62 0];
opts.StartPoint = [0.171186687811562 0.706046088019609 0.0318328463774207 0.27692298496089 0.0461713906311539 0.0971317812358475 0.823457828327293 0.694828622975817 0.317099480060861 0.950222048838355 0.0344460805029088];
opts.Upper = [Inf Inf Inf Inf 0.2 0.2 0.2 0.2 63 63 Inf];

% Fit model to data.
[fitresult, gof, output] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y400 vs. x400', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x400' );
ylabel( 'y400' );
grid on


