function [fitresult, gof, output] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Oct-2014 15:35:16


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'y0 + (AG/(wG*sqrt(2*pi)))*exp(-((x-xc)/(sqrt(2)*wG))^2) + (AL/pi)*(wL./((x-xc)^2 + wL^2)) + (AG2/(wG2*sqrt(2*pi)))*exp(-((x-xc2)/(sqrt(2)*wG2))^2) + (AL2/pi)*(wL2./((x-xc2)^2 + wL2^2))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0 0 0 42.8 43 0];
opts.MaxFunEvals = 800;
opts.MaxIter = 5000;
opts.StartPoint = [0.725182355023387 0.229886078857496 0.576053456321354 0.810628105007939 0.403843368384066 0.988439267199745 0.0899988149868883 0.320941032647761 0.511408938819178 0.0606063665682423 0.725687923545844];
opts.Upper = [10000000 10000000 100000 10000000 0.95 0.8 1 1 43 43.1 1000];

% Fit model to data.
[fitresult, gof, output] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
% figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 2, 3 );
h = plot( fitresult, xData, yData, '.k' );
set(h, 'linewidth', 1.5);
legend( h, 'Measured data', sprintf('Pseudo Voight fit\nR^2=%0.4f', gof.rsquare), 'Location', 'NorthEast' );
% Label axes
xlabel( '{\it{2\theta}} (°)', 'FontSize', 15  );
ylabel( 'Intensity (a. u.)', 'FontSize', 15 );
set(gca, 'fontsize', 13);
grid on

% % Plot residuals.
% subplot( 4, 2, 7 );
% h = plot( fitresult, xData, yData, 'residuals' );
% legend( h, 'Pseudo Voight fit - residuals', 'Zero Line', 'Location', 'NorthEast' );
% % Label axes
% xlabel( '{\it{2\theta}} (°)', 'FontSize', 13 );
% ylabel( 'Intensity (a. u.)', 'FontSize', 13 );
% set(gca, 'fontsize', 12);
% grid on


