function [fitresult, gof, output] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Oct-2014 16:29:42


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'y0 + (I/sqrt(pi*m*a))*(gamma(m)/gamma(m-0.5))*(1 + ((x-xc)^2)/(m*a^2))^(-m) + (I2/sqrt(pi*m2*a2))*(gamma(m2)/gamma(m2-0.5))*(1 + ((x-xc2)^2)/(m2*a2^2))^(-m2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [1000 1000 0 0 0 0 42.8 43 10];
opts.StartPoint = [0.11080932128715 0.407459507878399 0.884076806661962 0.548132777476588 0.369003076711617 0.208345982813347 0.440943276524324 0.956196152175878 0.124025916648043];
opts.Upper = [Inf 100000000 0.5 0.5 6 14 43 43.1 1000000];

% Fit model to data.
[fitresult, gof, output] = fit( xData, yData, ft, opts );

% Plot fit with data.
subplot( 2, 2, 4 );
h = plot( fitresult, xData, yData, '.k' );
set(h, 'linewidth', 1.5);
legend( h, 'Measured data', sprintf('Pearson VII fit\nR^2=%0.4f', gof.rsquare), 'Location', 'NorthEast' );
% Label axes
xlabel( '{\it{2\theta}} (°)' , 'fontsize', 15);
ylabel( 'Intensity (a. u.)', 'FontSize', 15  );
set(gca, 'fontsize', 13);
grid on

% % Plot residuals.
% subplot( 4, 2, 8 );
% h = plot( fitresult, xData, yData, 'residuals' );
% legend( h, 'Pearson VII fit - residuals', 'Zero Line', 'Location', 'NorthEast' );
% % Label axes
% xlabel( '{\it{2\theta}} (°)', 'FontSize', 13 );
% % ylabel( 'Intensity (a. u.)' );
% set(gca, 'fontsize', 12);
% grid on


