function [fitresult, gof, output] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Oct-2014 16:29:42


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'y0 + (I/sqrt(pi*m*a))*(gamma(m)/gamma(m-0.5))*(1 + ((x-xc)^2)/(m*a^2))^(-m) + (I2/sqrt(pi*m2*a2))*(gamma(m2)/gamma(m2-0.5))*(1 + ((x-xc2)^2)/(m2*a2^2))^(-m2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0 62.2 62.45 0];
opts.StartPoint = [0.392227019534168 0.655477890177557 0.171186687811562 0.706046088019609 0.0318328463774207 0.27692298496089 0.0461713906311539 0.0971317812358475 0.823457828327293];
opts.Upper = [100000 100000 0.5 0.5 100 100 62.4 62.8 1000];

% Fit model to data.
[fitresult, gof, output] = fit( xData, yData, ft, opts );

% Plot fit with data.
subplot( 2, 2, 4 );
h = plot( fitresult, xData, yData, '.k' );
set(h, 'linewidth', 1.5);
legend( h, 'Measured data', sprintf('Pearson VII\nR^2=%0.4f', gof.rsquare), 'Location', 'NorthEast' );
% Label axes
xlabel( '{\it{2\theta}} (°)' , 'fontsize', 15);
ylabel( 'Intensity (a. u.)', 'FontSize', 15  );
set(gca, 'fontsize', 13);
grid on

% % Plot residuals.
% subplot( 4, 2, 8 );
% h = plot( fitresult, xData, yData, 'residuals' );
% legend( h, 'Pearson VII fit - residuals', 'Zero Line', 'Location', 'NorthEast' );
% % Label axes
% xlabel( '{\it{2\theta}} (°)', 'FontSize', 13 );
% % ylabel( 'Intensity (a. u.)' );
% set(gca, 'fontsize', 12);
% grid on


