function [fitresult, gof, output] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Oct-2014 13:29:15


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [167960 62.388 0.0666879928344214 121937.071265037 62.514 0.0893980431590334];
opts.Upper = [Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof, output] = fit( xData, yData, ft, opts );

% Plot fit with data.
subplot( 2, 2, 1 );
h = plot( fitresult, xData, yData, '.k');
set(h, 'linewidth', 1.5);
legend( h, 'Measured data', sprintf('Gauss\nR^2=%0.4f', gof.rsquare), 'Location', 'NorthEast' );
% Label axes
xlabel( '{\it{2\theta}} (°)', 'FontSize', 15  );
ylabel( 'Intensity (a. u.)', 'FontSize', 15 );
set(gca, 'fontsize', 13);
grid on

% % Plot residuals.
% subplot( 4, 2, 3 );
% h = plot( fitresult, xData, yData, 'residuals' );
% legend( h, 'Gaussian fit - residuals', 'Zero Line', 'Location', 'NorthEast' );
% % Label axes
% % xlabel( '{\it{2\theta}} (°)' );
% ylabel( 'Intensity (a. u.)', 'FontSize', 13 );
% set(gca, 'fontsize', 12);
% grid on


